# Generated by Django 4.0.5 on 2022-06-30 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_column='name_first', max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, db_column='name_middle', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, db_column='name_last', max_length=100, null=True)),
                ('election_office', models.CharField(blank=True, db_column='election_office', max_length=250, null=True)),
                ('election_primary_date', models.DateField(blank=True, db_column='election_date_primary', null=True)),
                ('election_general_date', models.DateField(blank=True, db_column='election_date_general', null=True)),
                ('contact_email', models.EmailField(blank=True, db_column='email_contact', max_length=254, null=True)),
                ('media_email', models.EmailField(blank=True, db_column='email_media', max_length=254, null=True)),
                ('top_nav_logo', models.TextField(blank=True, db_column='logo_topnav', null=True)),
                ('donation_url', models.URLField(blank=True, db_column='url_donation', null=True)),
                ('twitter_url', models.URLField(blank=True, db_column='url_twitter', null=True)),
                ('facebook_url', models.URLField(blank=True, db_column='url_facebook', null=True)),
                ('instagram_url', models.URLField(blank=True, db_column='url_instagram', null=True)),
                ('youtube_url', models.URLField(blank=True, db_column='url_youtube', null=True)),
                ('vimeo_url', models.URLField(blank=True, db_column='url_vimeo', null=True)),
                ('site', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.site')),
            ],
        ),
    ]
