# Generated by Django 4.0.6 on 2022-07-29 19:38

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sharethetrail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignsite',
            name='footer_links',
            field=wagtail.fields.StreamField([('page_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='title', required=True)), ('page', wagtail.blocks.PageChooserBlock(label='Page', required=True))])), ('url_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='title', required=True)), ('url', wagtail.blocks.URLBlock(label='Link', required=True)), ('is_external_link', wagtail.blocks.BooleanBlock(label='Is External', required=False))])), ('email_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='title', required=True)), ('email_address', wagtail.blocks.EmailBlock(label='Email Address', required=True))])), ('phone_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='title', required=True)), ('phone_number', wagtail.blocks.CharBlock(label='Phone Number', required=True))])), ('sms_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='title', required=True)), ('phone_number', wagtail.blocks.CharBlock(label='Phone Number', required=True))]))], blank=True, db_column='links_footer', null=True),
        ),
        migrations.AlterField(
            model_name='campaignsite',
            name='top_nav_links',
            field=wagtail.fields.StreamField([('page_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='title', required=True)), ('page', wagtail.blocks.PageChooserBlock(label='Page', required=True))])), ('url_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='title', required=True)), ('url', wagtail.blocks.URLBlock(label='Link', required=True)), ('is_external_link', wagtail.blocks.BooleanBlock(label='Is External', required=False))])), ('email_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='title', required=True)), ('email_address', wagtail.blocks.EmailBlock(label='Email Address', required=True))])), ('phone_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='title', required=True)), ('phone_number', wagtail.blocks.CharBlock(label='Phone Number', required=True))])), ('sms_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='title', required=True)), ('phone_number', wagtail.blocks.CharBlock(label='Phone Number', required=True))]))], blank=True, db_column='links_top_nav', null=True),
        ),
    ]
