# Generated by Django 4.0.6 on 2022-08-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharethetrail', '0003_mapsnippet_alter_homepage_body_alter_webpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsite',
            name='aws_app_monitor_id',
            field=models.UUIDField(blank=True, db_column='aws_app_monitor_id', null=True),
        ),
        migrations.AddField(
            model_name='campaignsite',
            name='google_tag_id',
            field=models.CharField(blank=True, db_column='analytics_google_tag_id', max_length=30, null=True),
        ),
    ]
