# Generated by Django 4.0.6 on 2022-09-02 01:49

from django.db import migrations, models
import django.db.models.deletion
import sharethetrail.models.campaign


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0030_alter_coderedtag_tag'),
        ('sharethetrail', '0004_campaignsite_aws_app_monitor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('coderedpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coderedcms.coderedpage')),
                ('form_title', models.CharField(db_column='title_form', max_length=250)),
                ('success_message', models.CharField(db_column='message_success', max_length=250)),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=(sharethetrail.models.campaign.CampaignSitePageMixin, 'coderedcms.coderedpage'),
        ),
        migrations.CreateModel(
            name='SignUpPage',
            fields=[
                ('coderedpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coderedcms.coderedpage')),
                ('form_title', models.CharField(db_column='title', max_length=250)),
                ('success_message', models.CharField(db_column='message_success', max_length=250)),
                ('communication_enabled', models.BooleanField(db_column='type_communication_enabled')),
                ('merchandise_enabled', models.BooleanField(db_column='type_merchandise_enabled')),
                ('volunteer_enabled', models.BooleanField(db_column='type_volunteer_enabled')),
            ],
            options={
                'verbose_name': 'Sign Up Page',
            },
            bases=(sharethetrail.models.campaign.CampaignSitePageMixin, 'coderedcms.coderedpage'),
        ),
    ]
