version: 0.2

phases:
  pre_build:
    commands:
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - VERSION_TAG=$COMMIT_HASH
  build:
    commands:
      - docker build -t $REPOSITORY_URI:$VERSION_TAG -f ./docker/Dockerfile --build-arg SITE_TYPE=$SITE_TYPE --build-arg SITE_VERSION=$VERSION_TAG --build-arg STATIC_BUCKET_NAME=$STATIC_BUCKET_NAME --build-arg STATIC_CLOUDFRONT_DOMAIN=$STATIC_CLOUDFRONT_DOMAIN .
      - docker tag $REPOSITORY_URI:$VERSION_TAG $REPOSITORY_URI:latest
      - docker tag $REPOSITORY_URI:$VERSION_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPOSITORY_URI --all-tags
      - IMAGE_URI=$REPOSITORY_URI:$VERSION_TAG
      - printf '[{"name":"sharethetrail-site","imageUri":"%s"},{"name":"sharethetrail-site-migrate","imageUri":"%s"}]' $IMAGE_URI $IMAGE_URI > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json